trigger:
  - master
  - dev
pool:
  vmImage: macos-latest
steps:
  - bash: echo "GOCODER_SDK_KEY=\"$KEY\"" >> local.properties
    displayName: Create 'local.properties'
    env:
      KEY: $(GOCODER_SDK_KEY)

  - task: DownloadSecureFile@1
    name: google_services
    displayName: Download secure files
    inputs:
      secureFile: google-services.json

  - bash: mv $(google_services.secureFilePath) app/
    displayName: Create 'google-services.json'

  - task: Gradle@2
    displayName: Gradle build
    inputs:
      gradleOptions: '-Xmx4096m'
      javaHomeOption: JDKVersion
      jdkVersionOption: '1.8'
      jdkArchitectureOption: x64
      tasks: assembleRelease

  - task: Gradle@2
    displayName: Run Detekt
    inputs:
      tasks: detekt

  - task: Gradle@2
    displayName: Run Ktlint
    inputs:
      tasks: ktlint

  - task: Gradle@2
    displayName: Run Lint
    inputs:
      tasks: lintRelease

  - task: Gradle@2
    displayName: Run unit tests
    inputs:
      tasks: testReleaseUnitTest

  - task: DownloadSecureFile@1
    name: upload_keystore
    displayName: Download keystore
    inputs:
      secureFile: upload-keystore.jks

  - task: AndroidSigning@3
    displayName: Generate Android App Bundle
    inputs:
      apkFiles: '**/*.apk'
      apksignerKeystoreFile: upload-keystore.jks
      apksignerKeystorePassword: $(KEYSTORE_PASSWORD)
      apksignerKeystoreAlias: upload
      apksignerKeyPassword: $(KEY_PASSWORD)
      zipalign: true

  - task: PublishBuildArtifacts@1
    displayName: Publish build artifacts
    inputs:
      PathtoPublish: swabbr/build/outputs/apk/release
      ArtifactName: drop
      publishLocation: Container