import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
  const val com_github_bumptech_glide_compiler: String = "com.github.bumptech.glide:compiler:4.11.0"

  const val glide: String = "com.github.bumptech.glide:glide:4.11.0"

  const val adapter_rxjava2: String = "com.squareup.retrofit2:adapter-rxjava2:2.8.1"

  const val converter_moshi: String = "com.squareup.retrofit2:converter-moshi:2.8.1"

  const val retrofit: String = "com.squareup.retrofit2:retrofit:2.8.1"

  const val logging_interceptor: String = "com.squareup.okhttp3:logging-interceptor:3.14.7"

  const val okhttp: String = "com.squareup.okhttp3:okhttp:3.14.7"

  const val kotlin_android_extensions: String =
      "org.jetbrains.kotlin:kotlin-android-extensions:1.3.72"

  const val kotlin_android_extensions_runtime: String =
      "org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.3.72"

  const val kotlin_annotation_processing_gradle: String =
      "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:1.3.72"

  const val kotlin_reflect: String = "org.jetbrains.kotlin:kotlin-reflect:1.3.72"

  const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib:1.3.72"

  const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.72"

  const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.72"

  const val lifecycle_compiler: String = "androidx.lifecycle:lifecycle-compiler:2.2.0"

  const val lifecycle_extensions: String = "androidx.lifecycle:lifecycle-extensions:2.2.0"

  const val moshi_adapters: String = "com.squareup.moshi:moshi-adapters:1.8.0"

  const val moshi_kotlin: String = "com.squareup.moshi:moshi-kotlin:1.8.0"

  const val work_runtime_ktx: String = "androidx.work:work-runtime-ktx:2.3.1"

  const val work_rxjava2: String = "androidx.work:work-rxjava2:2.3.1"

  const val koin_android: String = "org.koin:koin-android:2.0.1"

  const val koin_androidx_viewmodel: String = "org.koin:koin-androidx-viewmodel:2.0.1"

  const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:4.1.2"

  const val io_gitlab_arturbosch_detekt_gradle_plugin: String =
      "io.gitlab.arturbosch.detekt:io.gitlab.arturbosch.detekt.gradle.plugin:1.12.0"

  const val de_fayard_buildsrcversions_gradle_plugin: String =
      "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:0.7.0"

  const val navigation_dynamic_features_fragment: String =
      "androidx.navigation:navigation-dynamic-features-fragment:2.3.4"

  const val navigation_safe_args_gradle_plugin: String =
      "androidx.navigation:navigation-safe-args-gradle-plugin:2.3.0"

  const val firebase_crashlytics_gradle: String =
      "com.google.firebase:firebase-crashlytics-gradle:2.3.0"

  const val runtime_permission_kotlin: String =
      "com.github.florent37:runtime-permission-kotlin:1.1.2"

  const val firebase_crashlytics_ktx: String = "com.google.firebase:firebase-crashlytics-ktx:17.2.2"

  const val navigation_fragment_ktx: String =
      "androidx.navigation:navigation-fragment-ktx:2.3.0-alpha01"

  const val firebase_analytics_ktx: String = "com.google.firebase:firebase-analytics-ktx:17.6.0"

  const val firebase_messaging_ktx: String = "com.google.firebase:firebase-messaging-ktx:20.3.0"

  const val leakcanary_android: String = "com.squareup.leakcanary:leakcanary-android:2.2"

  const val swiperefreshlayout: String = "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"

  const val detekt_formatting: String = "io.gitlab.arturbosch.detekt:detekt-formatting:1.7.0-beta2"

  const val legacy_support_v4: String = "androidx.legacy:legacy-support-v4:1.0.0"

  const val navigation_ui_ktx: String = "androidx.navigation:navigation-ui-ktx:2.3.0-alpha01"

  const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:1.1.3"

  const val circleimageview: String = "de.hdodenhof:circleimageview:3.1.0"

  const val google_services: String = "com.google.gms:google-services:4.3.4"

  const val camera_camera2: String = "androidx.camera:camera-camera2:1.0.0-beta03"

  const val mockito_inline: String = "org.mockito:mockito-inline:3.2.4"

  const val mockito_kotlin: String = "com.nhaarman.mockitokotlin2:mockito-kotlin:2.1.0"

  const val assertj_core: String = "org.assertj:assertj-core:3.15.0"

  const val core_testing: String = "androidx.arch.core:core-testing:2.1.0"

  const val firebase_bom: String = "com.google.firebase:firebase-bom:25.12.0"

  const val fragment_ktx: String = "androidx.fragment:fragment-ktx:1.2.4"

  const val toolargetool: String = "com.gu.android:toolargetool:0.3.0"

  const val imagepicker: String = "com.github.dhaval2404:imagepicker:1.7.2"

  const val lint_gradle: String = "com.android.tools.lint:lint-gradle:27.0.2"

  const val leonidslib: String = "com.plattysoft.leonids:LeonidsLib:1.3.2"

  const val viewpager2: String = "androidx.viewpager2:viewpager2:1.0.0"

  const val appcompat: String = "androidx.appcompat:appcompat:1.1.0"

  const val exoplayer: String = "com.google.android.exoplayer:exoplayer:2.10.5"

  const val jwtdecode: String = "com.auth0.android:jwtdecode:2.0.0"

  const val core_ktx: String = "androidx.core:core-ktx:1.5.0-alpha04"

  const val material: String = "com.google.android.material:material:1.1.0"

  const val rxkotlin: String = "io.reactivex.rxjava2:rxkotlin:2.4.0"

  const val rxpaper2: String = "com.github.pakoito:RxPaper2:1.4.0"

  const val rxjava: String = "io.reactivex.rxjava2:rxjava:2.2.17"

  const val aapt2: String = "com.android.tools.build:aapt2:4.0.2-6197926"

  const val junit: String = "junit:junit:4.13"
}
